//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineTravelGadgetsShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cartitem
    {
        public int CartItemsId { get; set; }
        public int CartId { get; set; }
        public int Quantity { get; set; }
        public int GadgetsId { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Gadget Gadget { get; set; }
    }
}
